rest:
  ssl: false
  host: localhost
  port: 8080
  nameSpace: /server
ui:
  releaseVersion: fakeReleaseVersion
  ssl: false
  # Can be used to prevent search engines from indexing the website (set to true to disable indexation).
  seNoIndex: false
  # Set to true to activate the google meta tag to get site ownership (control on the indexation).
  enableGoogleOwnershipTag: false
  # If enableGoogleOwnershipTag is set to true, set this property with google token.
  googleOwnershipTagValue: 'placeholder'
  # Default url to use to redirect to orcid.
  orcidUrl: https://orcid.org/

browseBy:
  showThumbnails: false

themes:
  - name: uclouvain
    headTags:
      - tagName: link
        attributes:
          rel: icon
          href: assets/uclouvain/images/favicons/uclouvain-favicon.png
          type: image/png

layout:
  navbar:
    showCommunityCollection: false
    showStatistics: false

languages: [
  { code: 'en', label: 'English', active: true },
  { code: 'fr', label: 'Français', active: true }
]

search:
  settings:
    renderOnServerSide: false
    showCharts: true
    showCsvExport: true
    showExport: true
    trackStatistics: true
    showSwitchConfiguration: true
    showInPlaceSearchSetting: true

submission:
  # disclaimerSectionFor: ['fakeIdToReplace']
  # DEV NOTES:
  #   We need to set as many 'fakeID' as they are `DSPACE_SUBMISSION_ENABLESHORTCUTPANELFOR_`environment variables.
  #   Without this fakeID, the `overrideWithEnvironment` (performing 'array' as 'object') can't determine there is a
  #   potential key to override by environment.
  #   This is an ugly workaround, but it works....
  enableShortcutPanelFor: ['fakeIdToReplace0', 'fakeIdToReplace1']
  # Trigger an autosave when changing a given metadata field
  # Works with all metadata schemas
  # However does not seem to work in form groups
  autosave:
    metadata: [
      'dc.contributor.author',
      'dc.contributor.advisor',
      'dc.identifier.doi',
      'dc.identifier.arxiv',
      'dc.identifier.pmid'
    ]
  dynamicFields:
    # * Dynamic voc config must contain:
    # *   -> The field that will trigger an API call
    # *   -> The API endpoint to contact
    # *   -> A list of data to include in the GET request
    # *
    # * The response will contain a JSON:
    # *   -> {
    # *   ->    'data-dc.degree.code': {
    # *   ->      'value': 'xxx',
    # *   ->      'options': ['xxx', 'yyy'],
    # *   ->    }
    # *   -> }
    # * (Config example below)

form:
  fields:
    year:
      minYearDelta: 100
      maxYearDelta: 2

item:
  showAccessStatuses: true
  citations:
    mainFormat: publication-uclouvain