rest:
  ssl: false
  host: localhost
  port: 8080
  nameSpace: /server
ui:
  ssl: false
  # Default url to use to redirect to orcid.
  orcidUrl: https://orcid.org/

browseBy:
  showThumbnails: false

themes:
  - name: uclouvain
    headTags:
      - tagName: link
        attributes:
          rel: icon
          href: assets/uclouvain/images/favicons/uclouvain-favicon.png
          type: image/png

layout:
  navbar:
    showCommunityCollection: false
    showStatistics: false

languages: [
  { code: 'en', label: 'English', active: true },
  { code: 'fr', label: 'Français', active: true }
]

search:
  settings:
    renderOnServerSide: false
    showCharts: true
    showCsvExport: true
    showExport: true
    trackStatistics: true
    showSwitchConfiguration: true
    showInPlaceSearchSetting: true

submission:
  # disclaimerSectionFor: ['fakeIdToReplace']
  enableShortcutPanelFor: ['fakeIdToReplace']
  # Trigger an autosave when changing a given metadata field
  # Works with all metadata schemas
  # However does not seem to work in form groups
  autosave:
    metadata: [
      # 'authors.identifier.fgs',
      'dc.contributor.author',
      # 'dc.identifier.doi',
      # 'masterthesis.degree.code',
      # 'masterthesis.faculty.code'
    ]
  dynamicFields:
    # * Dynamic voc config must contain:
    # *   -> The field that will trigger an API call
    # *   -> The API endpoint to contact
    # *   -> A list of data to include in the GET request
    # *
    # * The response will contain a JSON:
    # *   -> {
    # *   ->    'data-dc.degree.code': {
    # *   ->      'value': 'xxx',
    # *   ->      'options': ['xxx', 'yyy'],
    # *   ->    }
    # *   -> }
    # * (Config example below)

form:
  fields:
    year:
      minYearDelta: 100
      maxYearDelta: 2

item:
  showAccessStatuses: true
  citations:
    mainFormat: publication-uclouvain
  details:
    blocksConfig:
      book-block:
        heading: item.page.details.heading.book
        data:
          - label: item.page.details.label.pages
            field: publication.numberOfPages
            class: col-4
          - label: ISBN
            field: dc.identifier.isbn
            class: col-8
      collection-block:
        heading: item.page.details.heading.collection
        data:
          - label: item.page.details.label.name
            field: publication.collection.name
          - label: item.page.details.label.number
            field: publication.collection.number
            class: col-6
          - label: ISSN
            field: publication.collection.issn
            class: col-6
      conference-block:
        heading: item.page.details.heading.conference
        data:
          - label: item.page.details.label.name
            field: publication.conference.name
          - label: item.page.details.label.location
            field: publication.conference.location
          - label: item.page.details.label.start-date
            field: publication.conference.startDate
            class: col-6
          - label: item.page.details.label.end-date
            field: publication.conference.endDate
            class: col-6
      dissertation-block:
        heading: item.page.details.heading.dissertation
        data:
          - label: item.page.details.label.defense-date
            field: dissertation.defenseDate
          - label: item.page.details.label.faculty
            field: dissertation.faculty
          - label: item.page.details.label.degree
            field: dissertation.degree.name
      editor-block:
        heading: item.page.details.heading.editor
        data:
          - label: item.page.details.label.name
            field: publication.editor.name
          - label: item.page.details.label.location
            field: publication.editor.location
      host-document-block:
        heading: item.page.details.heading.host-document
        data:
          - label: item.page.details.label.title
            field: publication.host.title
          - label: item.page.details.label.pages
            field: publication.host.pages
            class: col-5
          - label: item.page.details.label.publication-date
            field: publication.host.dateIssued
            class: col-7
          - label: ISBN
            field: publication.host.isbn
      identifiers-block:
        heading: item.page.details.heading.identifiers
        data:
          - label: DOI
            field: dc.identifier.doi
          - label: Scopus ID
            field: dc.identifier.scopus
          - label: WOS ID
            field: dc.identifier.isi
          - label: Pubmed ID
            field: dc.identifier.pmid
          - label: arXiv ID
            field: dc.identifier.arxiv
          - label: ISMN
            field: dc.identifier.ismn
          - label: URI
            field: dc.identifier.uri
          - label: item.page.details.label.other
            field: dc.identifier.other
      journal-block:
        heading: item.page.details.heading.journal
        data:
          - label: item.page.details.label.title
            field: dc.relation.journal
          - label: item.page.details.label.volume
            field: publication.serial.volume
            class: col-12
          - label: item.page.details.label.issue
            field: publication.serial.issue
            class: col-12
          - label: item.page.details.label.date
            field: publication.serial.dateIssued
            class: col-6
          - label: ISSN
            field: publication.serial.issn
            class: col-6
      patent-block:
        heading: item.page.details.heading.patent
        data:
          - label: item.page.details.label.patent-office
            field: crispatent.patentOffice	
          - label: item.page.details.label.type
            field: crispatent.identifier.type
      report-block:
        heading: item.page.details.heading.report
        data:
          - label: item.page.details.label.pages
            field: publication.numberOfPages
      working-paper-block:
        heading: item.page.details.heading.working-paper
        data:
          - label: item.page.details.label.pages
            field: publication.numberOfPages
    typesConfig:
      text::book:
        - identifiers-block
        - book-block
        - editor-block
        - collection-block
      text::book-part:
        - identifiers-block
        - editor-block
        - collection-block
        - host-document-block
      text::conference-speech:
        - identifiers-block
        - conference-block
        - editor-block
        - collection-block
        - host-document-block
        - journal-block
      text::thesis:
        - identifiers-block
        - dissertation-block
      text::journal-article:
        - identifiers-block
        - journal-block
        - editor-block
      text::patent:
        - identifiers-block
        - patent-block
      text::report:
        - identifiers-block
        - report-block
        - editor-block
      text::working-paper:
        - identifiers-block
        - working-paper-block
        - collection-block